var EventEmitter = require("eventemitter3");

/**
 * Used by exported games to load into Gvbvdxx Game Maker 3.
 * The exported game data is generated by the interface.
 */
class GGM3ExportLoader extends EventEmitter {
  LOADING_PROGRESS = "LOADING_PROGRESS";
  LOADING_COMPLETE = "LOADING_COMPLETE";
  LOADING_ERROR = "LOADING_ERROR";

  /**
   * Creates a new ExportLoader instance.
   * @param {GGM3Engine} engine - The GGM3Engine instance to load the game into.
   * @param {Object} generated - The data from the exported game, this includes compiled code, sprites, costume urls, etc.
   */
  constructor(engine, generated) {
    super();
    this.engine = engine;
    this.generated = generated;
    this.maximum = 0;
    this.loaded = 0;
  }

  async startLoading() {
    var engine = this.engine;
    var generatedData = this.generated;
  }
}

module.exports = GGM3ExportLoader;
